In [2]:
import pandas as pd

customer_df = pd.read_csv(
    "../data/customer_details.csv"
)

customer_df.head()

,Customer_ID,Customer_Name,Gender,Age,City,State,Registration_Date,Last_Purchase_Date,Total_Orders,Purchase_Frequency,Total_Quantity_Purchased,Average_Basket_Size,Average_Order_Value,Total_Revenue,Customer_Lifetime_Value,Preferred_Category,Preferred_Channel,Customer_Segment,Loyalty_Status
0,CUST100000,Allison Hill,Male,51,Chennai,Tamil Nadu,2019-03-25,2026-05-05,21,2.90,252,12,3240.28,68045.88,68073.82,Fashion,Offline,Medium Value,Silver
1,CUST100001,Noah Rhodes,Female,47,Surat,Gujarat,2022-07-18,2025-06-22,8,2.04,48,6,200.00,1600.00,1602.96,Beauty,Offline,Low Value,Bronze
2,CUST100002,Angie Henderson,Female,27,Nashik,Maharashtra,2021-11-03,2026-03-06,10,2.16,90,9,1292.17,12921.70,12929.55,Electronics,Online,Low Value,Bronze
3,CUST100003,Daniel Wagner,Female,62,Nagpur,Maharashtra,2021-05-15,2026-06-03,40,7.84,560,14,3656.06,146242.40,146280.04,Beauty,Online,Medium Value,Gold
4,CUST100004,Cristian Santos,Female,31,Lucknow,Uttar Pradesh,2023-01-10,2026-05-10,50,14.51,850,17,3060.45,153022.50,153069.34,Grocery,Online,Medium Value,Gold

In [3]:
print(customer_df.columns.tolist())

['Customer_ID', 'Customer_Name', 'Gender', 'Age', 'City', 'State', 'Registration_Date', 'Last_Purchase_Date', 'Total_Orders', 'Purchase_Frequency', 'Total_Quantity_Purchased', 'Average_Basket_Size', 'Average_Order_Value', 'Total_Revenue', 'Customer_Lifetime_Value', 'Preferred_Category', 'Preferred_Channel', 'Customer_Segment', 'Loyalty_Status']

In [4]:
inventory_customer_df = pd.read_csv(
    "../data/customer_inventory_set.csv"
)

inventory_customer_df.head()

,Customer_ID,Customer_Name,Gender,Age,City,State,Registration_Date,Last_Purchase_Date,Total_Orders,Purchase_Frequency,...,Supplier_Name,Minimum_Order_Quantity,Safety_Stock,Inventory_Holding_Cost,Stockout_Cost,Priority_Category,Purchase_Cost,Unit_Cost,Inventory_Last_Updated_Date,Warehouse_Location
0,CUST100000,Allison Hill,Male,51,Chennai,Tamil Nadu,2019-03-25,2026-05-05,21,2.90,...,StyleHub Apparel Supply,65,7,29.77,1072.96,Medium,329.32,329.32,2026-06-14,Warehouse-C
1,CUST100001,Noah Rhodes,Female,47,Surat,Gujarat,2022-07-18,2025-06-22,8,2.04,...,Radiance Wholesale,18,9,60.49,2159.72,Low,450.54,450.54,2026-06-01,"Warehouse-C,Warehouse-D"
2,CUST100002,Angie Henderson,Female,27,Nashik,Maharashtra,2021-11-03,2026-03-06,10,2.16,...,Nova Electronics Supply,36,14,273.72,5746.51,Low,2227.27,2227.27,2026-06-06,Warehouse-D
3,CUST100003,Daniel Wagner,Female,62,Nagpur,Maharashtra,2021-05-15,2026-06-03,40,7.84,...,GlowSource Cosmetics,43,8,170.34,3239.36,Medium,1145.40,1145.40,2026-06-19,Warehouse-A
4,CUST100004,Cristian Santos,Female,31,Lucknow,Uttar Pradesh,2023-01-10,2026-05-10,50,14.51,...,Daily Needs Distributors,41,5,62.50,1208.77,Medium,369.98,369.98,2026-06-04,Warehouse-A

In [5]:
print(
    inventory_customer_df.columns.tolist()
)

['Customer_ID', 'Customer_Name', 'Gender', 'Age', 'City', 'State', 'Registration_Date', 'Last_Purchase_Date', 'Total_Orders', 'Purchase_Frequency', 'Total_Quantity_Purchased', 'Average_Basket_Size', 'Average_Order_Value', 'Total_Revenue', 'Customer_Lifetime_Value', 'Preferred_Category', 'Preferred_Channel', 'Customer_Segment', 'Loyalty_Status', 'Current_Stock_On_Hand', 'Lead_Time_Days', 'Supplier_Name', 'Minimum_Order_Quantity', 'Safety_Stock', 'Inventory_Holding_Cost', 'Stockout_Cost', 'Priority_Category', 'Purchase_Cost', 'Unit_Cost', 'Inventory_Last_Updated_Date', 'Warehouse_Location']

In [6]:
customer_df = pd.read_csv(
    "../data/customer_details.csv"
)

customer_df.head()

,Customer_ID,Customer_Name,Gender,Age,City,State,Registration_Date,Last_Purchase_Date,Total_Orders,Purchase_Frequency,Total_Quantity_Purchased,Average_Basket_Size,Average_Order_Value,Total_Revenue,Customer_Lifetime_Value,Preferred_Category,Preferred_Channel,Customer_Segment,Loyalty_Status
0,CUST100000,Allison Hill,Male,51,Chennai,Tamil Nadu,2019-03-25,2026-05-05,21,2.90,252,12,3240.28,68045.88,68073.82,Fashion,Offline,Medium Value,Silver
1,CUST100001,Noah Rhodes,Female,47,Surat,Gujarat,2022-07-18,2025-06-22,8,2.04,48,6,200.00,1600.00,1602.96,Beauty,Offline,Low Value,Bronze
2,CUST100002,Angie Henderson,Female,27,Nashik,Maharashtra,2021-11-03,2026-03-06,10,2.16,90,9,1292.17,12921.70,12929.55,Electronics,Online,Low Value,Bronze
3,CUST100003,Daniel Wagner,Female,62,Nagpur,Maharashtra,2021-05-15,2026-06-03,40,7.84,560,14,3656.06,146242.40,146280.04,Beauty,Online,Medium Value,Gold
4,CUST100004,Cristian Santos,Female,31,Lucknow,Uttar Pradesh,2023-01-10,2026-05-10,50,14.51,850,17,3060.45,153022.50,153069.34,Grocery,Online,Medium Value,Gold

In [7]:
customer_df["Last_Purchase_Date"] = pd.to_datetime(
    customer_df["Last_Purchase_Date"]
)

In [8]:
import pandas as pd

today = pd.Timestamp.today()

customer_df["Days_Since_Last_Purchase"] = (
    today
    - customer_df["Last_Purchase_Date"]
).dt.days

In [9]:
customer_df["Churn_Risk"] = "Low"

customer_df.loc[
    customer_df["Days_Since_Last_Purchase"] > 180,
    "Churn_Risk"
] = "High"

customer_df.loc[
    (
        customer_df["Days_Since_Last_Purchase"] > 90
    )
    &
    (
        customer_df["Days_Since_Last_Purchase"] <= 180
    ),
    "Churn_Risk"
] = "Medium"

In [10]:
customer_df.loc[
    (
        customer_df["Loyalty_Status"]
        == "Gold"
    )
    &
    (
        customer_df["Churn_Risk"]
        == "Medium"
    ),
    "Churn_Risk"
] = "Low"

In [11]:
customer_df["Churn_Risk"].value_counts()

Churn_Risk
Low       2513
High      1604
Medium     883
Name: count, dtype: int64

In [13]:
customer_df.to_csv(
    "../outputs/churn_predictions.csv",
    index=False
)

In [14]:
customer_df["Churn"].value_counts()

KeyError: 'Churn'

In [15]:
print(customer_df.columns.tolist())

['Customer_ID', 'Customer_Name', 'Gender', 'Age', 'City', 'State', 'Registration_Date', 'Last_Purchase_Date', 'Total_Orders', 'Purchase_Frequency', 'Total_Quantity_Purchased', 'Average_Basket_Size', 'Average_Order_Value', 'Total_Revenue', 'Customer_Lifetime_Value', 'Preferred_Category', 'Preferred_Channel', 'Customer_Segment', 'Loyalty_Status', 'Days_Since_Last_Purchase', 'Churn_Risk']

In [16]:
customer_df[[
    "Customer_ID",
    "Purchase_Frequency",
    "Total_Orders"
]].head()

  Customer_ID  Purchase_Frequency  Total_Orders
0  CUST100000                2.90            21
1  CUST100001                2.04             8
2  CUST100002                2.16            10
3  CUST100003                7.84            40
4  CUST100004               14.51            50

In [17]:
customer_df["Purchase_Frequency"].describe()

count    5000.000000
mean        7.382772
std         9.085317
min         0.500000
25%         1.750000
50%         4.180000
75%         9.332500
max        79.850000
Name: Purchase_Frequency, dtype: float64

In [18]:
customer_df["Churn"] = (
    customer_df["Purchase_Frequency"] < 2
).astype(int)

In [19]:
customer_df["Churn"].value_counts()

Churn
0    3589
1    1411
Name: count, dtype: int64

In [20]:
customer_df.to_csv(
    "../outputs/churn_predictions.csv",
    index=False
)

In [21]:
high_risk = customer_df[
    customer_df["Churn"] == 1
]

high_risk.head()

,Customer_ID,Customer_Name,Gender,Age,City,State,Registration_Date,Last_Purchase_Date,Total_Orders,Purchase_Frequency,...,Average_Order_Value,Total_Revenue,Customer_Lifetime_Value,Preferred_Category,Preferred_Channel,Customer_Segment,Loyalty_Status,Days_Since_Last_Purchase,Churn_Risk,Churn
7,CUST100007,Gina Moore,Male,30,Vadodara,Gujarat,2019-09-23,2025-12-06,5,0.74,...,835.65,4178.25,4171.64,Electronics,Online,Low Value,Bronze,200,High,1
9,CUST100009,Ryan Munoz,Male,37,Kochi,Kerala,2019-09-15,2026-02-15,3,0.50,...,1138.34,3415.02,3852.12,Fashion,Offline,Low Value,Bronze,129,Medium,1
11,CUST100011,Jamie Arnold,Male,30,Coimbatore,Tamil Nadu,2021-04-12,2025-09-13,2,0.50,...,1060.92,2121.84,2755.05,Grocery,Offline,Low Value,Bronze,284,High,1
12,CUST100012,Lisa Hensley,Female,28,Ahmedabad,Gujarat,2021-06-09,2026-02-01,1,0.50,...,1356.71,1356.71,3415.45,Home & Kitchen,Offline,Low Value,Bronze,143,Medium,1
25,CUST100025,Judy Baker,Female,26,Bengaluru,Karnataka,2021-05-17,2026-02-23,3,0.59,...,890.49,2671.47,2678.37,Grocery,Online,Low Value,Bronze,121,Medium,1

In [22]:
high_risk.to_csv(
    "../outputs/high_risk_customers.csv",
    index=False
)

In [23]:
customer_df["Churn"].value_counts()

Churn
0    3589
1    1411
Name: count, dtype: int64

In [24]:
customer_df["Churn"].value_counts(normalize=True) * 100

Churn
0    71.78
1    28.22
Name: proportion, dtype: float64